name: Showgirl Awakening
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4832806074991822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffe2e7'
    - '#fe92a7'
    - '#2d1b19'
    - '#f43b4c'
    - '#87271a'
  brandStrength: 0.6875
  lightness: 0.13784607429988682
  saturation: 0.625
  rhythmicContrast: 0.1809884801041335
purpose: []
