name: Showgirl Awakening
favicon: null
layout_spectrum: 1
typography_spectrum: 0.77067
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#00cea7'
    - '#ff4896'
    - '#ff91be'
    - '#97e9d5'
  brandStrength: 0.75
  lightness: 0.13784607429988682
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
